version: '3'

services:
  public:
    container_name: qazaq_public
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: public
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      # Add backend URL if needed, e.g.:
      # - NEXT_PUBLIC_API_URL=https://api.qazaq.kz

  cms:
    container_name: qazaq_cms
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: cms
    ports:
      - "3001:3000"
    restart: always
    environment:
      - NODE_ENV=production
      # - NEXT_PUBLIC_API_URL=https://api.qazaq.kz
