version: "3.8"

services:
  public:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: public
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "http://46.247.42.91:8000"
    ports:
      - "3000:3000"
    restart: unless-stopped

  cms:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: cms
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "http://46.247.42.91:8000"
    ports:
      - "3001:3000"
    restart: unless-stopped
