version: "3.8"

services:
  public:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: public
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api.qazaq.kz}
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api.qazaq.kz}
    ports:
      - "3000:3000"
    restart: unless-stopped

  cms:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: cms
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api.qazaq.kz}
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api.qazaq.kz}
    ports:
      - "3001:3000"
    restart: unless-stopped
